### ISSUE TITLE
Additional data to be added to census blocks

### ISSUE THREAD

**Issue by amandaaprahamian** [California-Data-Collaborative/CA-Water-Data-Challenge#2]
Currently, only usage data has been joined to the census block shape files.

Join the additional data to the shape files:
1. x miles from the beach
2. xxxx landscaped area
3. xxx people
4. xxx water saving improvements* 
5. total savings of $XXX*
6. competition details**
7. Your address is eligible for the XXX rebate program**
8. Here’s your goal: xxxxxx xxx xxxx**
9. Text and photos regarding stormdrain education*** (ex: Remember, your stormdrains drain excess outdoor watering directly to the ocean, this outfall drains your neighborhood water into the nearest stream…see photos here...)

*what is our time frame for these numbers? in the last year? the last 5 years? I suggest a time period that gives us impressive numbers, but is easy to take in (so maybe not 5 long years)?
**applicable only if unique to census blocks. if water district wide, we can add text about it to the web app without needing it joined to the shape files
***some census blocks have no outfalls in view. we need to decide what to write in this section for those census blocks (we could just make it general and have stock photos of outfalls for these census blocks).

**Comment by leighphan** [comment]
Hi @amandaaprahamian, could you further specify the parameter descriptions?

- Is 'landscaped area' the total area in the census block with drought-resistant landscaping?
- '3. xxx people' refers to population within the census block?

**Comment by patwater** [comment]
Sorry for the delay.  We're on this internally though and will get back to you ASAP.  CC @monobina @dmarulli @datwater

**Comment by monobina** [comment]
I just shared the link to the data with @amandaaprahamian 
cc @patwater @datwater @dmarulli

**Comment by monobina** [comment]
@amandaaprahamian let us know if you need anything else

**Comment by amandaaprahamian** [comment]
@monobina thanks! I can't quite tell what the column names stand for. Does [this link](https://california-data-collaborative.carto.com/tables/bfh5gpcbwjq4lzh0_census_block_usage/public/map) include information about miles from the beach, landscaped area, # of people, # of water saving improvements, total saving$, competition details, the different rebate programs, and individual or overall goals?

**Comment by monobina** [comment]
@amandaaprahamian  hhsize column stands for the household size, irr_area_sf is the irrigated area of of the household,usage_et_amount is the ET information, and usage_ccf is their water usage. I think this data does not have miles from beach but should be easy to calculate with the geiod in GIS? Looks like this specific data does not have the rebate details. @dmarulli @patwater @datwater do we have any ready to share data yet with the rebate programs and water savings details @amandaaprahamian is asking for?

**Comment by monobina** [comment]
Looking at the data i think the hhsize is number of people in that census block and irr_area_sf is the total irrigated area in the block? Correct me if I am wrong @dmarulli

**Comment by dmarulli** [comment]
Hey, that's correct @monobina. And just to be explicit, we arrive at those values aggregating up from the customer-level. This allows us track any changes at the census block-level with monthly granularity as opposed to decadal granularity (the frequency with which block-level data are released by the US Census Bureau). One can still use the geoid column to join with any relevant Census data of course.

**Comment by monobina** [comment]
Thanks @dmarulli ! This makes sense

**Comment by amandaaprahamian** [comment]
@monobina what are the units of usage_ccf (water usage)? Is it per capita or total for that census block? @leighphan

**Comment by monobina** [comment]
@dmarulli  do you know what are the units of usage_ccf  in the data? is it per capita or total for the census block?

**Comment by dmarulli** [comment]
Total usage for the month (each record represents a single month) @monobina @amandaaprahamian @leighphan

**Comment by patwater** [comment]
And @monobina usage_ccf is in ccf I believe

**Comment by monobina** [comment]
@patwater yes it's ccf

**Comment by patwater** [comment]
Great do you all have the data you need?

**Comment by monobina** [comment]
I did not receive any link to the data yet.

**Comment by christophertull** [comment]
I thought I sent an email last week @monobina. Maybe it didn't go through? will resend now.

**Comment by monobina** [comment]
I did not find any email with the data. It could be that it bounced back.

**Comment by monobina** [comment]
@christophertull received your dropbox data link now
