### ISSUE TITLE
Update on Data Needs

### ISSUE THREAD

**Issue by amandaaprahamian** [California-Data-Collaborative/CA-Water-Data-Challenge#7]
An update for Issue #2:

_1. x miles from the beach_   -   @leighphan could we calculate this using mapbox? @monobina had said it would be easy to calculate using the geoid in GIS.

_2. xxxx landscaped area_   -   [this link](https://california-data-collaborative.carto.com/tables/bfh5gpcbwjq4lzh0_census_block_usage/public/map) has irr_area_sf (Irrigated Area of the Household). We should use the average for water year 2015-2016. @monobina when is this data from? The last census?

_3. xxx people_   -   [this link](https://california-data-collaborative.carto.com/tables/bfh5gpcbwjq4lzh0_census_block_usage/public/map) has hhsize (Household Size). We should use the average for water year 2015-2016. @monobina when is this data from? The last census?

_4. xxx water saving improvements_   -   @monobina any updates for #'s 4 - 8?
_5. total savings of $XXX_
_6. competition details_
_7. Your address is eligible for the XXX rebate program_
_8. Here’s your goal: xxxxxx xxx xxxx_

_9. Text and photos regarding stormdrain education_ (ex: Remember, your stormdrains drain excess outdoor watering directly to the ocean, this outfall drains your neighborhood water into the nearest stream…see photos here...)   -   @amandaaprahamian will work with OCPW to determine the best verbage for here.

*New* (see Issue #6) 

- _10. Last water year (July 2015-2016), your neighborhood used an average of XXXX gallons of water above what it needed each month._   -    use [TotalInefficiency.csv](https://github.com/California-Data-Collaborative/CA-Stormwater-Data-Challenge/blob/master/Data%20and%20initial%20R%20code/TotalInefficiency.csv) to average monthly inefficiency. Decide whether we want this and if yes, address first comment in Issue #6
- _11. Last water year (July 2015-2016), your neighborhood's biggest usages were in April and June. The smallest usages were in XXXX and XXXX._   -   find in [TotalInefficiency.csv](https://github.com/California-Data-Collaborative/CA-Stormwater-Data-Challenge/blob/master/Data%20and%20initial%20R%20code/TotalInefficiency.csv)
- _12. Your neighborhood typically uses XX% of its water budget._   -  find in [WeightedAverageEfficiency.csv ](https://github.com/California-Data-Collaborative/CA-Stormwater-Data-Challenge/blob/master/Data%20and%20initial%20R%20code/WeightedAverageEfficiency.csv)

**Comment by patwater** [comment]
Nothing to add though just want to say this is a great job breaking down the tasks and advancing the project!

**Comment by monobina** [comment]
@amandaaprahamian I think for both (2) and (3), landscape area & household size,  is aggregated from our billing data. It's a time series starting from 2011 going upto 2016  @christophertull please correct me if I am wrong on this.

**Comment by monobina** [comment]
@christophertull do you have a cleaned up date for 4-6 that @amandaaprahamian is asking for? If not we can work on this data to get it out to them

**Comment by monobina** [comment]
@amandaaprahamian can you elaborate a bit more on your requirements for 4-6? Are you looking for a yearly information on this for the past year? I am not sure how much granular we can get on this data.

**Comment by patwater** [comment]
For the turf water savings and cost effectiveness numbers you could always use this study or the one UCR did: [Final water savings of turf removal KDD (CaDC).pdf](https://github.com/California-Data-Collaborative/CA-Stormwater-Data-Challenge/files/904134/Final.water.savings.of.turf.removal.KDD.CaDC.pdf)

**Comment by christophertull** [comment]
Yes, @monobina is correct about points 2/3. This is landscape area and household size for each customer from MNWD billing system and then aggregated up to the block level.

re: 4-6, we have your rebate data in a clean form from 2008 - Jan 2016. How much of that is public and could be shared? Could imagine doing something like aggregating the counts of different rebate types, or summing over dollars of rebates issued.

**Comment by monobina** [comment]
Thanks @patwater @christophertull . Yes, those studies might be useful.  I don't think customer level data is public. We can aggregate it to the census block level for the variables - number of rebate programs offered, average price of rebate, number of participants etc. @amandaaprahamian do you think a data with these info  will be helpful or any other thoughts/suggestions?

**Comment by patwater** [comment]
@amandaaprahamian @leighphan circling back to see what else you need on this :)
